### PR TITLE
Notify users of integrations (once) if/when appropriate

### PR DESCRIPTION
**Pull request by nomeyer**
The plugin works best with the GitHub and/or Jira integrations set up (so it displays & uses information about PRs & issues), so we notify users when appropriate to let them know that the integrations exist. We only notify once.

When is appropriate?
- The user is familiar with the plugin – currently defined as >= 5 gutters toggled & popovers viewed
- The user likely does not have any of the integrations set up – currently defined as not a single PR or issue was displayed in the tooltips viewed by the user
- The user has not seen this notification before
- The user has just shown the gutter in a file (so we don't interrupt them in the middle of something)

### CODE REVIEW

**Comment by nomeyer** [comment]
Actually instead of looking for PRs & issues just in the tooltips shown, I should be looking at all the data available for each displayed gutter. Will look into doing that tomorrow.

**Comment by pthm** [comment]
All looks good, the cleanup in `GutterItem.tsx` is nice.

Only thing I would change is to have a single localStorage object in `IntegrationNotification.ts` and use `JSON.stringify()` & `JSON.parse()` to serialise / deserialise it instead of having 4 individual items with `getItem` & `setItem` everywhere to manage the state

**Comment by nomeyer** [comment]
Should be good to go now – changed the `localStorage` data structure & updated the logic to check for integration data across the gutters instead of just the tooltips.

**Comment by pthm** [comment]
lgtm 👍 

Changed the base branch to `next` so it now needs some conflicts resolved then we're good to go

**Pull request merged**
