### PR TITLE
Implement gutter age tooltip

### PR DESCRIPTION
**Pull request by pthm**
Implements the tooltip when hovering over the age gutter to display a graph representing where between repo creation and today the commit lies.

Moves the existing blame tooltip into a separate component and implements a new one for the age tooltip.

Also changes the way the age indicator in the gutter is rendered, it is no longer a border and instead a separate DOM element.

screen shot 2017-09-29 at 14 57 29

### CODE REVIEW

**Comment by nomeyer** [comment]
Looking good! Found one minor issue (commit icon alignment) and one bigger issue (commit placement on tooltip doesn't match gutter colour).

**Commit icon alignment**

screen shot 2017-09-29 at 15 07 13
screen shot 2017-09-29 at 15 08 22

**Placement doesn't match gutter colour**

screen shot 2017-09-29 at 15 08 22

This is line 19 of the plugin's `index.ts` on this branch.

**Comment by jaredjburgess** [comment]
Going to give it a spin now and then checkout the code

**Comment by jaredjburgess** [comment]
screen shot 2017-09-29 at 16 22 28

Looking good, will look over the code now.

On a side note before testing this I uninstalled and reinstalled my atom setup (which ended up fixing the commit / pr labels being too high).

**Comment by jaredjburgess** [comment]
Code looks standard, nothing stood out as strange or unreasonable. Some doc strings / comments could be added in a few places but we shouldn't delay the release for that.

**Comment by nomeyer** [comment]
Good to go 👍

**Pull request merged**
